= Custom Development Container Base Image
:toc:
:source-highlighter: highlight.js

== About

A custom https://containers.dev/[Development Container] base image packed with as many as necessary and as few as possible configurations and applications to make development a breeze.

This image is built for `amd64` and `arm64`.

== Additional Setup

=== Proper Caching

To properly persist data that should be cached, you need to provide volumes in `devcontainer.json` for the following directories:

[source,json]
----
{
  // Persist the VS Code Server cache (e.g. for extensions)
  "source": "<PROJECT>-cache-vscode_server",
  "target": "/home/ubuntu/.vscode-server",
  "type": "volume"
},
{
  // Persist the `${HOME}/.cache` directory
  "source": "<PROJECT>-cache-home_cache",
  "target": "/home/ubuntu/.cache",
  "type": "volume"
}
----

=== Image Entrypoint & Setup

[NOTE]
====
We do not set a custom `ENTRYPOINT` with this image because

. the entrypoint is overwritten by Development Containers anyway, and
. we want to make the additional setup optional.
====

There is a script that you can execute via

[source,json]
----
"postCreateCommand": "/usr/local/devcontainer_base/bin/entrypoint.sh"
----

in your `devcontainer.json` file. link:entrypoint.sh[This script] performs additional setup procedures:

. Run all scripts in `/usr/local/devcontainer_base/init_scripts/` if there are any. You can copy scripts into this directory when you build on top of this image, or you can mount a volume to this directory.
